name: deploy_backend

on:
  push:
    branches: [main]
    paths:
    - 'backend/**'

env:
  AZURE_FUNCTIONAPP_NAME: GetCVCounter  # Set this to your Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend/api'   # Path to your Azure Function App project
  DOTNET_VERSION: '6.0.x'  # Set this to the .NET version you're using

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # This uses the correct secret you've added

      - name: 'Setup DotNet ${{ env.DOTNET_VERSION }} Environment'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Run Unit Tests'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/../tests'  # Adjust path if needed
          dotnet test


      - name: Set CosmosDB Connection String
        shell: bash
        run: echo "AZURE_COSMOSDB_CONNECTION_STRING='${{ secrets.AZURE_COSMOSDB_CONNECTION_STRING }}'" >> $GITHUB_ENV
   
      - name: 'Deploy Azure Functions App'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
